### ISSUE TITLE
Error when installed on fresh CRA

### ISSUE THREAD

**Issue by bkrausz** [blocks/blocks#101]
When trying to add this on a fresh CRA (via `yarn add blocks-ui`) one gets the following error:

```
./node_modules/blocks-ui/dist/index.js
Module not found: Can't resolve '@blocks/blocks/src' in '.../node_modules/blocks-ui/dist'
```

I'm still getting up to speed on the crazy world of npm packaging, so unfortunately I haven't been able to dig much deeper than that.

**Comment by johnletey** [comment]
@bkrausz Run `yarn add @blocks/blocks` and then try again? I don't know if this will work, it's just an idea.

**Comment by bkrausz** [comment]
Thanks for the quick reply! That doesn't work, apparently because it doesn't know how to transpile the package:

```
./node_modules/@blocks/blocks/src/footers/basic.js
SyntaxError: .../node_modules/@blocks/blocks/src/footers/basic.js: Unexpected token (8:4)

   6 | const FooterBasic = ({ justifyContent = 'space-between', ...props }) => {
   7 |   return (
>  8 |     <footer
```

**Comment by johnletey** [comment]
@bkrausz My pleasure. Do you mind pushing all of the code you currently have to a repository so that I can play around with it locally?

**Comment by bkrausz** [comment]
Gladly: https://github.com/bkrausz/blocks-ui-playground

**Comment by johnletey** [comment]
@bkrausz After playing with it for a little bit, it seems like the CRA setup doesn't like the `footer`, `header`, etc components in the built in blocks.

@johno I an utterly perplexed, have any clue what is going on?

**Comment by johno** [comment]
Ah, yeah so blocks-ui is importing the components from src rather than the root. It’s cruft from when I was developing initially.

https://github.com/blocks/blocks/blob/master/packages/blocks-ui/src/index.js#L7

**Comment by johnletey** [comment]
@johno Ah, gotcha. Do you want me to open up a quick pull request? Or do you just want to add this to master by yourself?

**Comment by johno** [comment]
A pr would be great!

**Comment by johnletey** [comment]
@bkrausz Can you try your current code with `v0.0.36`? It's being released as I'm typing this.

**Comment by bkrausz** [comment]
Looks good! I also needed to do `yarn add @blocks/blocks @mdx-js/react` to get it to work. I'll submit a PR for the setup instructions when I'm back at a desk.
