### ISSUE TITLE
wrong editor body font-family

### ISSUE THREAD

**Issue by souporserious** [blocks/blocks#142]
In some scenarios when switching to the viewports view, the font-family gets messed up.

![image](https://user-images.githubusercontent.com/2762082/70158248-c7588380-166b-11ea-8989-7602b87cae82.png)

It looks like it should be a simple fix of applying `font-family: system-ui` to the body.

**Comment by jordanoverbye** [comment]
That's weird - I can try and have a look at this over the next few days

**Comment by johnletey** [comment]
This is something that I've noticed as well, and was introduced in #86.

**Comment by jordanoverbye** [comment]
Hmm, I can't seem to reproduce. What browser and OS? @johnletey @souporserious

**Comment by souporserious** [comment]
I've seen it in Chrome and Safari. Unfortunately, it happens somewhat randomly, but almost always when switching to the viewports tab. The body font-family isn't set when I last checked which seems to be the underlying issue. Should be a good first issue for someone if they want to take it 😃

**Comment by johnletey** [comment]
> Hmm, I can't seem to reproduce. What browser and OS? @johnletey @souporserious

@jordanoverbye Sorry for the late reply, but I am using MacOS Mojave with Safari.
