### ISSUE TITLE
when in "code mode" should be able to edit the code by hand. 

### ISSUE THREAD

**Issue by jstacoder** [blocks/blocks#144]
this would be for easily adding children 
and adding props not supported in the editor

i could look at adding a PR

**Comment by johno** [comment]
We'd love to accept a PR for this!

**Comment by johnletey** [comment]
If it's cool with everyone, I would love to pick this up and start working on it

**Comment by johno** [comment]
Go for it @johnletey, thanks!

**Comment by johnletey** [comment]
You're welcome @johno! If anyone wants to track my progress, check out my [`editable-code`](https://github.com/johnletey/blocks/tree/editable-code) branch.

**Comment by johnletey** [comment]
@johno I have added a toggle button for making the code box editable. Now I just need to update the code whenever the user makes changes.

Am I correct when I say that I will have to update three different code items?

https://github.com/blocks/blocks/blob/master/packages/blocks-ui/src/index.js#L97-L99

Is there any way of easily doing this?
