### ISSUE TITLE
editor outline view

### ISSUE THREAD

**Issue by souporserious** [blocks/blocks#146]
It would be awesome to have an outline view similar to [VS code](https://code.visualstudio.com/updates/v1_24#_outline-view) or a simple layers panel. We could also add the ability to toggle the display property on components as well like design tools allow.

**Comment by colebemis** [comment]
I implemented a prototype of a layers panel:

![Kapture 2019-12-22 at 16 28 06](https://user-images.githubusercontent.com/4608155/71329307-55d85c00-24d8-11ea-9ab9-d9a6984f2aa8.gif)

https://twitter.com/colebemis/status/1208750509609213953

Gonna start putting together a PR 👍
