### ISSUE TITLE
Module not found: Can't resolve '../../../lerna.json' 

### ISSUE THREAD

**Issue by danielsousaio** [blocks/blocks#156]
Compilation error when running `yarn start`.

```
Failed to compile

./node_modules/blocks-ui/dist/header.js
Module not found: Can't resolve '../../../lerna.json' in '/home/daniel/code/screen-editor/node_modules/blocks-ui/dist'
```

Seems like the issue was introduced on this commit:
https://github.com/blocks/blocks/commit/5333f4b1a82d0ef78ececfdf9a7471f090885bea#diff-2b4d43d51f360ddfd79c8596b9a871feR5

**Comment by johno** [comment]
Should be fixed in 0.0.54, thanks for opening the issue!
