### ISSUE TITLE
The entire canvas should be droppable

### ISSUE THREAD

**Issue by johno** [blocks/blocks#197]
Right now you can only drop a block by the other blocks. The whole canvas area should be droppable.

**Comment by Caryyon** [comment]
@johno just to make sure i'm understanding this. 
We want the whole canvas area (middle section) to be droppable. meaning we can drop something anywhere an it will click to the bottom of the last block?

**Comment by johno** [comment]
Yep, exactly! The primary pain point is that you can't arbitrarily drop below the existing components in the canvas. If there's a large open space, we should be able to drop anywhere beneath it.
