### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by axe312ger** [blocks/blocks#25]
Hey,

wanted to take a look at the code and do some hacky prototyping. Unfortunately, the demo does not run since a few 0.x versions. I always get this:

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug
```

The error disappears when I comment out `<Editor />` which may mean its related to react-slate.

Any ideas?

Thanks a bunch,
Benedikt

**Comment by axe312ger** [comment]
A gatsby info might help:

```
$ gatsby info

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Firefox: 65.0.1
    Safari: 12.1
  npmGlobalPackages:
    gatsby-cli: 2.5.9
    gatsby-dev-cli: 2.4.15
```

**Comment by johno** [comment]
How are you running the demo? Right now it'll likely best run as a yarn workspace:

```sh
yarn
yarn workspace demo start
```

Let me know if that works!

**Comment by axe312ger** [comment]
Hey, deleting the node modules and running yarn again helped :)

I did run in another problem, but could solve it:

```
Node(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```

The demo passes null as initialValue to the editor when localStorage is empty. I guess we should add a default value here to avoid this issue.

After hacking in a value in the editor, the page is running :)

**Comment by johno** [comment]
Ah yeah that’s a bug 🐛. We should def add in a default value that doesn’t explode. Would gladly accept a PR!

**Comment by wbunting** [comment]
Demo is currently down on the deployed site with error https://mdx-blocks.com/demo/

```
ve(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```

Maybe this PR needs to be deployed?

**Comment by axe312ger** [comment]
I can confirm, demo broken. Blank screen after 1 second @johno

**Comment by rchrdnsh** [comment]
Confirming this as well for me in Chrome, Firefox and Safari. Nothing shows up for the demo, just a blank white screen at:

https://mdx-blocks.com/demo/

Just blank, but if hit refresh i see the demo UI for a split second, and the nit's gone again.

**Comment by axe312ger** [comment]
looks like you fixed it @johno  👍
