### ISSUE TITLE
Improve lazy loading spinner design

### ISSUE THREAD

**Issue by jordanoverbye** [blocks/blocks#250]
The spinner when you switch mode is a bit boring. Would be nice to add some color, animations or something like that 🎨

**Comment by johnletey** [comment]
Might be worth using one of the spinners from this PR: https://github.com/system-ui/theme-ui/pull/599

**Comment by mathieudutour** [comment]
It could be a good opportunity to use the logo: make the small cube loops through all the corners of the bigger one or something like that.

**Comment by mathieudutour** [comment]
maybe something like this: https://codepen.io/mathieudutour/full/vYEwqPr
