### ISSUE TITLE
Boolean control type does not appear

### ISSUE THREAD

**Issue by raunofreiberg** [blocks/blocks#303]
I'm using the basic example from [Blocks UI documentation](https://blocks-ui.com/docs/controls), as such:

```
const Component = ({ isTomato, ...props }) => (
	<h1
		{...props}
		style={{
			color: isTomato ? 'tomato' : 'inherit'
		}}
	/>
)

applyPropertyControls(Component, {
	isTomato: {
		type: ControlType.Boolean,
		title: 'Tomato'
	}
})
```

Yet, the `isTomato` prop does not appear for me in the editor panel.

**Comment by raunofreiberg** [comment]
To me, it seems like `ControlType.Boolean` properties aren't being added to the controls in https://github.com/blocks/blocks/blob/ec4c09d8412f3f4e8d922ca64126742ef382729a/packages/blocks-ui/src/property-controls-panel.js#L54?

**Comment by blenderskool** [comment]
@johno Can I try working on this?

**Comment by johnletey** [comment]
> Can I try working on this?

@blenderskool As far as I know no-one is working on this - go for it 🎉

**Comment by johno** [comment]
Yeah, looks like I never got around to adding the last control type @raunofreiberg 🙃 

Yep, that'd be great if you wanted to get a fix in @blenderskool!

**Comment by cheng-kang** [comment]
@blenderskool @johno didn't see a PR yet so just raised one, hope you don't mind
