### ISSUE TITLE
Overflowing image on home page

### ISSUE THREAD

**Issue by blenderskool** [blocks/blocks#313]
The demo image is overflowing horizontally on the home page.
Screenshot:
![blocks-ui com_](https://user-images.githubusercontent.com/21107799/76139966-a5f8a080-607b-11ea-87f2-32938d2990bd.png)

**Comment by johnletey** [comment]
@blenderskool Thank you for bringing this to our attention 🙏 I can reproduce this, debugging now - should just be something to do with the site css 🤔

**Comment by blenderskool** [comment]
It's a simple fix, I had it almost ready

**Comment by johnletey** [comment]
> I had it almost ready

Awesome, always accepting PRs 👍
