### ISSUE TITLE
Styles from theme file not being applied

### ISSUE THREAD

**Issue by blenderskool** [blocks/blocks#317]
Follow up from https://github.com/blocks/blocks/pull/316#issuecomment-596184095
The styles from the [theme file](https://github.com/blocks/blocks/blob/master/src/gatsby-plugin-theme-ui/index.js#L39-L41) aren't applied to `layout.js` and `minimal-layout.js`.
This may be the cause for #313

**Comment by johnletey** [comment]
What's weird is that some styles from the theme file are applied, but others (like the `img` styles) aren't 😕

**Comment by johno** [comment]
This has been fixed. The problem was the result of conflicting versions of emotion 🙃 

Thanks for opening up this issue!
