### ISSUE TITLE
Cannot commit a docs update: ERROR: Permission to blocks/blocks.git denied

### ISSUE THREAD

**Issue by jpvajda** [blocks/blocks#352]
Hello Blocks Team

I was going to make a Docs update I 

1. cloned the blocks master repo
2. made my change on a new branch called docs_update_4.01.20 
3. committed the change. 

However I can't seem to push this change to a new remote branch in this repo. Is this restricted or am I just missing a step here? 

```
Johns-MacBook-Pro:blocks jvajda$ git push -u origin docs_update_4.01.20
ERROR: Permission to blocks/blocks.git denied to jpvajda.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Johns-MacBook-Pro:blocks jvajda$
```

**Comment by jletey** [comment]
@jpvajda you have to fork the repository to your account first, and then clone that repository - as outside contributors don’t have direct push access to the repository (for obvious security reasons haha)

**Comment by jpvajda** [comment]
@jletey  Thanks!

**Comment by jletey** [comment]
@jpvajda my pleasure, looking forward to seeing your contributions :)
