### ISSUE TITLE
RFC: Use Feather icons instead of Material UI icons

### ISSUE THREAD

**Issue by johnletey** [blocks/blocks#37]
I see that you guys are using Material UI icons. May I suggest [Feather](https://feathericons.com) instead?

And, since I don't think that Feather currently has all of the icons required, I could design them (as I have designed [quite a few](https://github.com/feathericons/feather/pulls/johnletey) icons for Feather recently) and then add them to Feather and then this project!

Would really love to help contribute to this project! Both this and the desktop app seem very promising!

**Comment by jxnblk** [comment]
> since I don't think that Feather currently has all of the icons required

IIRC this is why we went with Material Design icons. I love Feather, but personally I'd also like an easy way for this part of the UI to be customizable so that any icon or text labels could be used for things like the toolbars
