### ISSUE TITLE
Update serializer for Slate v0.47

### ISSUE THREAD

**Issue by johno** [blocks/blocks#40]
We're currently using [`slate-mdast-serializer`](https://github.com/orbiting/mdast/tree/master/packages/slate-mdast-serializer) but it likely makes sense to use our own, MDX-specific serializer. While we port the current serializer over we can ditch the `leaves` usage since that has been removed.

**Comment by kristojorg** [comment]
Just installed and tried to run the demo, getting `cannot read property length of undefined` where undefined is `leaves`. Betting this has to do with you transition? Suggestions what I should do to get up and running so I can fiddle around?
