### ISSUE TITLE
Can't get the Demo to run.

### ISSUE THREAD

**Issue by tizzle** [blocks/blocks#42]
I currently cannot get the demo to run. Gatsby compiles with a few linter warnings, but there is a runtime error in the `visitLeaves` function of slate-mdast-serializer:

```
TypeError: Cannot read property 'length' of undefined
visitLeaves
node_modules/slate-mdast-serializer/lib/index.js:84
```

Any idea on how to fix this?

Thanks!

**Comment by axe312ger** [comment]
There are several issues in the master branch, some are fixed in the rewrite branch.

I was not able to get any of these two branches running in the current state of the project :(
