### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by rchrdnsh** [blocks/blocks#44]
Hi @johno XD

Just curious if this is something that is still in development.

Cheers,

Richard

**Comment by axe312ger** [comment]
Same. 

I think the project is stuck here: https://github.com/blocks/blocks/pull/41

I'd love to help out, get the project running again and start adding the features I have in mind.

@johno afaik u pretty busy, can U maybe update us on the state of this project, what needs to be done to get it running again and where we can help?

🙇

**Comment by axe312ger** [comment]
Wohow we have progress in here <3

**Comment by johno** [comment]
We're moving again so going to go ahead and close this now : )

**Comment by rchrdnsh** [comment]
XD
