### ISSUE TITLE
When deleting a component, everything is unselected

### ISSUE THREAD

**Issue by ChristopherBiscardi** [blocks/blocks#71]
When deleting components off the page, the selection state is completely lost. Something should stay selected, ideally something within the same group as a similar position in the tree.

![delete](https://user-images.githubusercontent.com/551247/69609360-2d933580-0fde-11ea-88ea-dd1c7a71c6e0.gif)

**Comment by johnletey** [comment]
@ChristopherBiscardi How does this look?

![Kapture 2019-11-26 at 8 41 52](https://user-images.githubusercontent.com/30328854/69613095-d8c8dc80-1028-11ea-94b8-1c5bbd9bb6f7.gif)

**Comment by ChristopherBiscardi** [comment]
Works for me, shipppitttt
