### ISSUE TITLE
size-related value inputs

### ISSUE THREAD

**Issue by ChristopherBiscardi** [blocks/blocks#72]
The padding, etc size related values are currently number inputs. It would be nice if these were step-sliders or something that 

A) locked possible values to the values in the theme
B) allows switching between "in theme" and "out of theme" states (that is, using the 1st, 2nd, 3rd theme value or using 4px, 15px, 33px)

![image](https://user-images.githubusercontent.com/551247/69609809-3e907680-0fdf-11ea-9fa1-10e2f6fe8495.png)

**Comment by stuartfavretto** [comment]
Cool, yah when I was using the demo I was thinking the same thing with using sliders to select from the available theme variables.

For the pixel based value entry idea my mind starts wandering into all the different places where the "in/out of theme" button would need to be provided if that norm is established. Do you think it is too bold of a product decision to say the only place pixel values can be entered is in the theme declaration area, then when building screens the user must use theme variables?

I started laying out some rough ideas, and noticed that in the case the user unlinks all sides if we use sliders it could start taking up a lot of space, so maybe it's better to go with some sort of text input that can go inline?

![marginIdeas](https://user-images.githubusercontent.com/14082465/70383573-ecc3e680-1924-11ea-8632-fa48d491ca31.png)
