### ISSUE TITLE
Sometimes colors are semantic names and sometimes hex colors

### ISSUE THREAD

**Issue by ChristopherBiscardi** [blocks/blocks#74]
The issue is: It's hard to determine why one or the other is used

```js
sx={{
  color: "#3333ee",
  bg: "muted"
}}
```

![image](https://user-images.githubusercontent.com/551247/69610458-b9a65c80-0fe0-11ea-9c28-62f73e3e18a3.png)

**Comment by jxnblk** [comment]
Think this might be a bug in `@theme-ui/editor` and how it attempts to look up the color's key and falls back to the raw value if it's not found

**Comment by jordanoverbye** [comment]
@jxnblk Yeah it is. I've just opened a PR to fix that
