### ISSUE TITLE
Discoverability of element trees

### ISSUE THREAD

**Issue by ChristopherBiscardi** [blocks/blocks#75]
When dragging in demo components, I can click on various visual aspects of the component (such as children) however, it's hard to get an overview of what the component *is*.

It could be nice to add a simplified sub-tree view of the tree below the selected component that extends beyond the current simplified "children view"

![image](https://user-images.githubusercontent.com/551247/69613476-78b14680-0fe6-11ea-853c-a11a55ae5059.png)

**Comment by johnletey** [comment]
Is this at all related to #62?

**Comment by johno** [comment]
It's _somewhat_ related to #45, but I believe Chris is more referring to providing additional tree information on the selected node. Though, I'm not 100% sure what the best way to expose that is 🤔

**Comment by ChristopherBiscardi** [comment]
yeah, this is about additional tree information so that it's easier to figure out what makes up the component, not better previews
