### ISSUE TITLE
Other UI in demo is effected by `Theme`

### ISSUE THREAD

**Issue by jordanoverbye** [blocks/blocks#90]
If you change the theme in the `Theme` panel to something like `Tosh`, some of the UI gets updated unexpectedly such as:

- The fonts and spacing in the `Editor` panel are effected
- The code modal

I would expect when changing the theme, that only the Components in the Editor will update, not the whole UI.

**Screenshot**
<img width="1730" alt="Screen Shot 2019-11-27 at 8 47 39 am" src="https://user-images.githubusercontent.com/6265154/69678912-979cff00-10f2-11ea-8cd0-15b47a3d6a5b.png">

**Comment by johno** [comment]
Yeah, this is definitely a bug. I've joked with @jxnblk that we need a `@theme-ui/ui` that mimics Theme UI's API with a new context but can be used for other tooling so it doesn't collide.

**Comment by jxnblk** [comment]
Yeah, we should make sure the `@theme-ui/editor` package has its own scoped theme that doesn't pick up the theme used in the preview/renderer IMO
