### ISSUE TITLE
Catch syntax errors in source JSX and display on the canvas

### ISSUE THREAD

**Issue by johno** [blocks/blocks#96]
If the JSX passed to Blocks is invalid, it currently crashes the app. We should catch the syntax error and nicely display the babel's output in the canvas.

**Comment by coffee-cup** [comment]
I think this was fixed by https://github.com/blocks/blocks/pull/100? Unless we don't want to close until some of the improvements suggested in that PR are in.

**Comment by johno** [comment]
I think the last thing we need to do to close this issue is catch errors when invalid JSX is passed directly to the editor as the src prop. That case still causes the editor to crash.

**Comment by johnletey** [comment]
> That case still causes the editor to crash.

It does: https://github.com/blocks/blocks/issues/59#issuecomment-559125385
